version: '3.8'
services:
  db:
    image: postgres:15
    container_name: sgi_db
    restart: always
    environment:
      POSTGRES_USER: sgiuser
      POSTGRES_PASSWORD: sgi123
      POSTGRES_DB: sgi
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: sgi_backend
    ports:
      - '3001:3001'
    depends_on:
      - db

  frontend:
    build: ./apps/frontend
    container_name: sgi_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres_data: